### ISSUE TITLE
Images removed from category still show up. 

### ISSUE THREAD

**Issue by fnielsen** [WikimediaChile/stats-wlm#2]
Images removed from category still show up. 

https://stats.wikilovesmonuments.cl/2018/denmark/detail?user=Fnielsen

https://commons.wikimedia.org/wiki/File:Str%C3%B8mhuset,_2018-09-16.jpg

**Comment by dennistobar** [comment]
@fnielsen the script has updated a lot of things. Can you check if the issue persist? Thanks!
