### ISSUE TITLE
Please delete this page

### ISSUE THREAD

**Issue by harukatsuki** [WikimediaChile/stats-wlm#3]
I don't want this page lived on the Internet. Please delete it. Thanks a lot.

https://stats.wikilovesmonuments.cl/2018/taiwan/detail?user=%E9%AC%BC%E6%98%8E%E6%9C%88

**Comment by dennistobar** [comment]
Hi, I just forwarding all traffic to Wiki Loves X page. Please refer them if you need delete some page.
